server:
  database_url: sqlite:///./sql_app.db?check_same_thread=False
  admin_token: token

preacher:
  schedules:
    - '0 9 * * *'
  receivers:
    - name: line
      type: line-channel
      secret: <secret>
