server:
  database_url: sqlite:///./sql_app.db?check_same_thread=False
  #  database_url: mysql+pymysql://root:1234@localhost/marco79423-jessigod
  admin_token: token

bots:
  line_bot:
    channel_access_token: <token>
    channel_secret: <secret>
  telegram_bot:
    url: <url>
    token: <token>
    bot_username: <username>
  slack_bot:
    webhook_url: <token>
preacher:
  schedules:
    - '0 9 * * *'

