### 成功取得所有来源
GET {{host}}/api/origins

### 新增名言
POST {{host}}/api/sayings
Authorization: Jessi bac

{
  "origin": "西卡姐",
  "content": "至尊敬的大能且所向披靡又太強甚至是最強而且還很愛笑的高嶺之花"
}

### 成功取得隨機名言
GET {{host}}/api/random-saying

### 成功取得隨機名言
GET {{host}}/api/random-saying?origin=西卡姐

### 成功取得所有名言
GET {{host}}/api/sayings

### 成功取得所有名言
GET {{host}}/api/sayings?pageIndex=0&editorOnly=1
Authorization: Jessi bac

### 成功取得所有名言
GET {{host}}/api/sayings?origin=西卡姐
Authorization: Jessi bac

### 成功取得所有名言
GET https://jessigod.marco79423.net/api/sayings?origin=西卡姐
Authorization: Jessi bac

### 成功取得所有名言

GET https://jessigod.marco79423.net/api/sayings?origin=Nabi 姐
Authorization: Jessi bac

### 修改名言
PUT {{host}}/api/sayings/2f029d50-3108-450b-8cdb-4a1a60b6542c
Authorization: Jessi bac

{
  "origin": "origin",
  "content": "content"
}

### 傳播名言
POST {{host}}/api/propagation-tasks
Authorization: Jessigod token

{
   "mode": "random"
}

### 傳播名言
POST {{host}}/api/propagation-tasks
Authorization: Jessigod token

{
   "mode": "specific",
   "data": {
     "sayingID": ""
   }
}

### 傳播名言
POST {{host}}/api/propagation-tasks
Authorization: Jessigod token

{
   "mode": "direct",
   "data": "今天在創造另一個世界，所以晚了點"
}


### 聊天

PUT {{host}}/api/chat

{
   "question": "推薦一個領導人"
}
