name: Build backend docker image

on:
  push:
    tags:
      - '*'
    paths:
      - backend/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 設定環境
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 建置和推送
      - name: Get Version
        run: |
          export VERSION=${GITHUB_REF#refs/*/}
          echo "::env VERSION=${VERSION}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build backend image
        run: |
          echo "::env VERSION=${{env.VERSION}}"

          docker build \
            --file backend/Dockerfile \
            --build-arg REPO_VERSION=${{env.VERSION}} \
            --tag marco79423/jessigod-backend:latest \
            .
      - name: Push backend image
        run: |
          echo "::env VERSION=${{env.VERSION}}"

          docker push marco79423/jessigod-backend:latest

          docker tag marco79423/jessigod-backend:latest marco79423/jessigod-backend:${{env.VERSION}}
          docker push marco79423/jessigod-backend:${{env.VERSION}}
